# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Univision_app', '0002_auto_20160326_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
